### PR TITLE
(Temporarily) fixed overswiping on discover page

### PR DESCRIPTION
**Pull request by calixo888**
Fixed the overswiping issue with the ion-slide on the discover page by selecting certain slidesPerView values that work with certain screen widths and displaying them based on screen width breakpoints. Not a good fix, but a fix nonetheless.

### CODE REVIEW

**Comment by calixo888** [comment]
Have completely finished the overswiping issue with mathematical dynamic values

**Comment by calvinckho** [comment]
@calixo888 I am playing with the Mentors slider and it looks worse than before (i.e. I don't like the mentors card taking the whole width of the screen). Can you revert the change for the Mentors slider? I think I want to keep it fixed width and don't bother with the over swiping there.

Can you instead only implement your dynamic calculation on the Me page Mentors/Mentees sliders and the Community Slider? So revert all the changes in Discover and only do the dynamic calculation on the Me page sliders. 

Thanks!

**Comment by calixo888** [comment]
Alright, I assume you want me to implement the dynamic calculations for the mobile design for the me page because that's the only time on the me page sliders are used.

**Comment by calvinckho** [comment]
Yes that’s correct! Thanks.

**Comment by calixo888** [comment]
@calvinckho the overswiping issue doesn't exist on mobile for the me page, so I just revoked the changes on the discover page and that's it.

**Comment by calvinckho** [comment]
This issue only applies to the swiping of mentors on Desktop view. The proper UI should be clicking on show left and show right buttons and not drag-swiping so needs to do a more comprehensive redesign.

**Pull request closed without merging**
