### PR TITLE
Intern-challenge-kevin tolentino

### PR DESCRIPTION
**Pull request by kevin-tolentino**
Hi Calvin,

Here is my completed implementation of the intern-challenge. I will attach a before and after screenshot of the implementation. I used Chrome Dev Tools to see the changes in the browser while implementing the feature. Thank you for letting me do this challenge. Please let me know if any change requests are needed, and I will work on completing them.

As a note, I've never worked with Ionic UI components, Sass variables, or Angular before, so it was interesting to use and read a bit of the Ionic documentation while also viewing a little bit of the Angular code. I usually work with React and Bootstrap for styling, so it was nice to see some similarities while also noticing the differences.

**Before**:
intern-challenge-before-implementation

**After**:
intern-challenge-finished-implementation

Looking forward to hearing your feedback.

Best Regards,
Kevin Tolentino

### CODE REVIEW

**Comment by calvinckho** [comment]
Hi Kevin, thanks for the great job! You must be using dark mode on your machine. Can you also take care of when light mode is on?

Screen Shot 2020-08-10 at 5 13 07 PM

**Comment by kevin-tolentino** [comment]
Fixed color change when on light mode or dark mode on Windows OS setting:

intern-challenge-kevin-tolentino-color-fix

**Comment by kevin-tolentino** [comment]
Hi @calvinckho, I just made the changes. Attached above is a gif of what it looks like with the changes implemented. Please let me know if any other changes are needed!

**Comment by calvinckho** [comment]
thanks Kevin. Great work!

**Pull request closed without merging**
